# Generated by Django 4.2.5 on 2023-11-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_writercategory"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="categories",
        ),
        migrations.AddField(
            model_name="subscription",
            name="categories_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscribed",
                to="categories.category",
            ),
        ),
    ]
