# Generated by Django 4.2.5 on 2023-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("verification_code", models.TextField(null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
