# Generated by Django 4.2.5 on 2023-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_verificationemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationemail",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name="verificationemail",
            name="verification_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
