# Generated by Django 4.2.5 on 2023-11-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("is_successfully_sent", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        through="categories.EmailCategory", to="categories.category"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writer_email",
                        to="accounts.writerprofile",
                    ),
                ),
            ],
        ),
    ]
