# Generated by Django 4.2.5 on 2023-10-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("writer", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(null=True)),
                ("is_successfully_sent", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
