# Generated by Django 4.2.5 on 2023-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="edited_at",
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name="email",
            name="sent_at",
            field=models.DateTimeField(
                default=models.DateTimeField(auto_now_add=True), null=True
            ),
        ),
    ]
