# Generated by Django 4.2.5 on 2023-11-03 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0002_alter_email_edited_at_alter_email_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="email",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="email",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="email",
            name="is_sent",
        ),
        migrations.RemoveField(
            model_name="email",
            name="is_successfully_sent",
        ),
        migrations.RemoveField(
            model_name="email",
            name="sent_at",
        ),
    ]
