# Generated by Django 4.2.5 on 2023-11-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0003_remove_email_created_at_remove_email_edited_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="email",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="email",
            name="is_successfully_sent",
            field=models.BooleanField(default=False),
        ),
    ]
