# Generated by Django 4.2.5 on 2023-11-03 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0004_email_is_read_email_is_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="email",
            name="sent_at",
            field=models.DateTimeField(null=True),
        ),
    ]
