# Generated by Django 4.2.5 on 2023-11-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_writercategory"),
        ("mails", "0005_email_created_at_email_edited_at_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="categories",
            field=models.ManyToManyField(
                through="categories.EmailCategory", to="categories.category"
            ),
        ),
    ]
