# Generated by Django 4.2.5 on 2023-11-13 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mails", "0005_email_created_at_email_edited_at_email_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_email",
                        to="categories.category",
                    ),
                ),
                (
                    "email_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_category",
                        to="mails.email",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="related_mails",
            field=models.ManyToManyField(
                through="categories.EmailCategory", to="mails.email"
            ),
        ),
    ]
