# Generated by Django 4.2.5 on 2023-11-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WriterCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_writer",
                        to="categories.category",
                    ),
                ),
                (
                    "writer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writer_category",
                        to="accounts.writerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_email",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
