# Generated by Django 4.2.5 on 2023-11-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mails", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcategory",
            name="email_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_category",
                to="mails.email",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="related_mails",
            field=models.ManyToManyField(
                through="categories.EmailCategory", to="mails.email"
            ),
        ),
    ]
